"""removed social

Revision ID: 1cc3487a2d5b
Revises: 2379dc128d44
Create Date: 2020-08-15 22:18:18.242404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc3487a2d5b'
down_revision = '2379dc128d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_social', type_='unique')
        batch_op.drop_column('social')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social', sa.VARCHAR(length=64), nullable=False))
        batch_op.create_unique_constraint('uq_user_social', ['social'])

    # ### end Alembic commands ###
