"""added comment

Revision ID: 25057c4d3d0a
Revises: 4c9011c87471
Create Date: 2020-08-31 16:58:51.445132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25057c4d3d0a'
down_revision = '4c9011c87471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comment', 'user', ['author_id'], ['id'])
    op.drop_column('comment', 'author')
    op.drop_column('comment', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('title', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('comment', sa.Column('author', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    # ### end Alembic commands ###
