"""added SearCHABLE Mixin and interfaced with both User and POst Model




Revision ID: 365ea2366d76
Revises: 98615c6f5088
Create Date: 2020-09-06 20:42:41.530431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '365ea2366d76'
down_revision = '98615c6f5088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_facebook_user_username', table_name='facebook_user')
    op.drop_table('facebook_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facebook_user',
    sa.Column('social_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('social_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uq_facebook_user_username', 'facebook_user', ['username'], unique=True)
    # ### end Alembic commands ###
