"""added comment

Revision ID: 4c9011c87471
Revises: 7336795cccdf
Create Date: 2020-08-31 16:55:25.768471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c9011c87471'
down_revision = '7336795cccdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'user', ['author_id'], ['id'])
    op.drop_column('comment', 'title')
    op.drop_column('comment', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('author', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('comment', sa.Column('title', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    # ### end Alembic commands ###
