"""added social removed nullable false arg added password

Revision ID: 55538652375d
Revises: 57358537cb3c
Create Date: 2020-08-16 13:27:58.453752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55538652375d'
down_revision = '57358537cb3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)

    # ### end Alembic commands ###
