"""added phone_number

Revision ID: 63b8ae348991
Revises: 8db756c8bd93
Create Date: 2020-08-26 15:24:17.571611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b8ae348991'
down_revision = '8db756c8bd93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.Integer(), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=60))
        batch_op.create_unique_constraint(batch_op.f('uq_user_phone_number'), ['phone_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_phone_number'), type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
