"""added messages

Revision ID: 7a1adf24c578
Revises: c95436b17183
Create Date: 2020-09-14 19:13:36.103814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a1adf24c578'
down_revision = 'c95436b17183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('date_read', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_post_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_post_read_time')
    op.drop_column('post', 'date_read')
    # ### end Alembic commands ###
