"""added post_notifs

Revision ID: 8db756c8bd93
Revises: d2fdf21bf73c
Create Date: 2020-08-21 20:18:10.387461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db756c8bd93'
down_revision = 'd2fdf21bf73c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receive_notifs', sa.Boolean(), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=60))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.drop_column('receive_notifs')

    # ### end Alembic commands ###
