"""added methods for save and unsave posts

Revision ID: 98615c6f5088
Revises: 77c2ea850143
Create Date: 2020-08-31 22:48:41.727842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98615c6f5088'
down_revision = '77c2ea850143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_posts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'saved_posts', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'saved_posts', type_='foreignkey')
    op.drop_column('saved_posts', 'user_id')
    # ### end Alembic commands ###
