"""added comment

Revision ID: 99a072b492f1
Revises: 9e8ce258c1d1
Create Date: 2020-08-31 16:46:15.863653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99a072b492f1'
down_revision = '9e8ce258c1d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('author_id', sa.String(length=100), nullable=True))
    op.drop_index('fk_comment_post_id_user', table_name='comment')
    op.create_foreign_key(None, 'comment', 'user', ['author_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    op.drop_column('comment', 'title')
    op.drop_column('comment', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('author', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('comment', sa.Column('title', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_index('fk_comment_post_id_user', 'comment', ['post_id'], unique=False)
    op.drop_column('comment', 'author_id')
    # ### end Alembic commands ###
