"""added password configs

Revision ID: 9cb07d2b0791
Revises: 365ea2366d76
Create Date: 2020-09-08 23:21:27.594096

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9cb07d2b0791'
down_revision = '365ea2366d76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password', sa.String(length=60), nullable=True))
    op.drop_index('uq_user_password', table_name='user')
    op.create_unique_constraint(None, 'user', ['_password'])
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=60), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('uq_user_password', 'user', ['password'], unique=True)
    op.drop_column('user', '_password')
    # ### end Alembic commands ###
