"""added comment

Revision ID: be681f355ce5
Revises: 826e902f9a25
Create Date: 2020-08-31 17:05:37.855961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be681f355ce5'
down_revision = '826e902f9a25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('connection')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('provider_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('provider_user_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('access_token', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('secret', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('display_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('profile_url', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('image_url', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('rank', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_connection_user_id_user'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('comment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('date_posted', mysql.DATETIME(), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('author_id', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='comment_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
