"""added suport for private messages

Revision ID: c95436b17183
Revises: fabc9f0196b8
Create Date: 2020-09-14 12:25:51.209363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c95436b17183'
down_revision = 'fabc9f0196b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_message_read_time', sa.DateTime(), nullable=True))
    op.drop_index('_password', table_name='user')
    op.create_unique_constraint(None, 'user', ['password'])
    op.drop_column('user', '_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password', mysql.VARCHAR(length=60), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('_password', 'user', ['_password'], unique=True)
    op.drop_column('user', 'last_message_read_time')
    # ### end Alembic commands ###
