"""changed password field

Revision ID: cdccdff93349
Revises: 63b8ae348991
Create Date: 2020-08-27 16:13:31.629395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cdccdff93349'
down_revision = '63b8ae348991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.create_unique_constraint(op.f('uq_user_password'), 'user', ['password'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_password'), 'user', type_='unique')
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    # ### end Alembic commands ###
