"""changed post column

Revision ID: ddc1473ca2bf
Revises: c2970c62631d
Create Date: 2020-08-27 23:03:35.678073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ddc1473ca2bf'
down_revision = 'c2970c62631d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('tag', sa.String(length=100), nullable=False))
    op.drop_column('post', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('post', 'tag')
    # ### end Alembic commands ###
