"""changed password column

Revision ID: fabc9f0196b8
Revises: 9cb07d2b0791
Create Date: 2020-09-09 10:58:32.926458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fabc9f0196b8'
down_revision = '9cb07d2b0791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=60), nullable=True))
    op.drop_index('_password', table_name='user')
    op.create_unique_constraint(None, 'user', ['password'])
    op.drop_column('user', '_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password', mysql.VARCHAR(length=60), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('_password', 'user', ['_password'], unique=True)
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
